const FileList = {};

FileList.SHIP_FILES = [
  "galactic-empire/arquitens-class-command-cruiser.json",
  "galactic-empire/arquitens-class-light-cruiser.json",
  "galactic-empire/gladiator-i-class-star-destroyer.json",
  "galactic-empire/gladiator-ii-class-star-destroyer.json",
  "galactic-empire/gozanti-class-assault-carriers.json",
  "galactic-empire/gozanti-class-cruisers.json",
  "galactic-empire/imperial-i-class-star-destroyer.json",
  "galactic-empire/imperial-ii-class-star-destroyer.json",
  "galactic-empire/imperial-star-destroyer-cymoon-1-refit.json",
  "galactic-empire/imperial-star-destroyer-kuat-refit.json",
  "galactic-empire/interdictor-combat-refit.json",
  "galactic-empire/interdictor-suppression-refit.json",
  "galactic-empire/quasar-fire-i-class-cruiser-carrier.json",
  "galactic-empire/quasar-fire-ii-class-cruiser-carrier.json",
  "galactic-empire/raider-i-class-corvette.json",
  "galactic-empire/raider-ii-class-corvette.json",
  "galactic-empire/victory-i-class-star-destroyer.json",
  "galactic-empire/victory-ii-class-star-destroyer.json",

  "rebel-alliance/assault-frigate-mark-ii-a.json",
  "rebel-alliance/assault-frigate-mark-ii-b.json",
  "rebel-alliance/cr90-corvette-a.json",
  "rebel-alliance/cr90-corvette-b.json",
  "rebel-alliance/gr-75-combat-retrofits.json",
  "rebel-alliance/gr-75-medium-transports.json",
  "rebel-alliance/hammerhead-scout-corvette.json",
  "rebel-alliance/hammerhead-torpedo-corvette.json",
  "rebel-alliance/mc30c-scout-frigate.json",
  "rebel-alliance/mc30c-torpedo-frigate.json",
  "rebel-alliance/mc75-armored-cruiser.json",
  "rebel-alliance/mc75-ordnance-cruiser.json",
  "rebel-alliance/mc80-assault-cruiser.json",
  "rebel-alliance/mc80-battle-cruiser.json",
  "rebel-alliance/mc80-command-cruiser.json",
  "rebel-alliance/mc80-star-cruiser.json",
  "rebel-alliance/modified-pelta-class-assault-ship.json",
  "rebel-alliance/modified-pelta-class-command-ship.json",
  "rebel-alliance/nebulon-b-escort-frigate.json",
  "rebel-alliance/nebulon-b-support-refit.json"
];

FileList.SQUADRON_FILES = [
  "galactic-empire/aggressor-assault-fighter.json",
  "galactic-empire/boba-fett.json",
  "galactic-empire/bossk.json",
  "galactic-empire/colonel-jendon.json",
  "galactic-empire/darth-vader.json",
  "galactic-empire/dengar.json",
  "galactic-empire/firespray-31.json",
  "galactic-empire/gar-saxon.json",
  "galactic-empire/howlrunner.json",
  "galactic-empire/ig-88.json",
  "galactic-empire/jumpmaster-5000.json",
  "galactic-empire/lambda-class-shuttle.json",
  "galactic-empire/maarek-stele.json",
  "galactic-empire/major-rhymer.json",
  "galactic-empire/mandalorian-gauntlet-fighter.json",
  "galactic-empire/mauler-mithel.json",
  "galactic-empire/morna-kee.json",
  "galactic-empire/soontir-fel.json",
  "galactic-empire/tie-advanced-squadron.json",
  "galactic-empire/tie-bomber-squadron.json",
  "galactic-empire/tie-defender-squadron.json",
  "galactic-empire/tie-fighter-squadron.json",
  "galactic-empire/tie-interceptor-squadron.json",
  "galactic-empire/tie-phantom-squadron.json",
  "galactic-empire/vt-49-decimator.json",
  "galactic-empire/whisper.json",
  "galactic-empire/yv-666.json",

  "rebel-alliance/a-wing-squadron.json",
  "rebel-alliance/b-wing-squadron.json",
  "rebel-alliance/corran-horn.json",
  "rebel-alliance/dash-rendar.json",
  "rebel-alliance/dutch-vander.json",
  "rebel-alliance/e-wing-squadron.json",
  "rebel-alliance/han-solo.json",
  "rebel-alliance/hera-syndulla.json",
  "rebel-alliance/hwk-290.json",
  "rebel-alliance/jan-ors.json",
  "rebel-alliance/ketsu-onyo.json",
  "rebel-alliance/keyan-farlander.json",
  "rebel-alliance/lancer-class-pursuit-craft.json",
  "rebel-alliance/lieutenant-blount.json",
  "rebel-alliance/luke-skywalker.json",
  "rebel-alliance/nym.json",
  "rebel-alliance/scurrg-h-6-bomber.json",
  "rebel-alliance/tycho-celchu.json",
  "rebel-alliance/vcx-100-freighter.json",
  "rebel-alliance/wedge-antilles.json",
  "rebel-alliance/x-wing-squadron.json",
  "rebel-alliance/y-wing-squadron.json",
  "rebel-alliance/yt-1300.json",
  "rebel-alliance/yt-2400.json",
  "rebel-alliance/z-95-headhunter-squadron.json"
];

FileList.UPGRADE_FILES = [
  "commander.json",
  "defensive-retrofit.json",
  "experimental-retrofit.json",
  "fleet-command.json",
  "fleet-support.json",
  "ion-cannons.json",
  "offensive-retrofit.json",
  "officer.json",
  "ordnance.json",
  "support-team.json",
  "title.json",
  "turbolasers.json",
  "weapons-team-and-offensive-retrofit.json",
  "weapons-team.json"
];

module.exports = FileList;
