import CommandTest from './Command.test.js';
import DamageCardTest from './DamageCard.test.js';
import DefenseTokenTest from './DefenseToken.test.js';
import DiceValueTest from './DiceValue.test.js';
import DistanceTest from './Distance.test.js';
import EnumUtilitiesTest from './EnumUtilities.test.js';
import FactionTest from './Faction.test.js';
import HullZoneTest from './HullZone.test.js';
import PhaseTest from './Phase.test.js';
import PlayFormatTest from './PlayFormat.test.js';
import RangeTest from './Range.test.js';
import ReferenceCardTest from './ReferenceCard.test.js';
import SelectorTest from './Selector.test.js';
import ShipBaseTest from './ShipBase.test.js';
import ShipCardTest from './ShipCard.test.js';
import SquadronCardTest from './SquadronCard.test.js';
import UpgradeCardTest from './UpgradeCard.test.js';
import UpgradeSlotTest from './UpgradeSlot.test.js';

QUnit.start();
